### ISSUE TITLE
Interactive Drawings with SketchRNN Link Broken

### ISSUE THREAD

**Issue by peilingjiang** [shiffman/Intro-ML-Arts-IMA#69]
The link in week 7 assignment instruction leads to 404 page of p5 web editor.

**Comment by shiffman** [comment]
Thank you! I believe I fixed this with https://github.com/ml5js/Intro-ML-Arts-IMA/commit/449526ccc4ef4285ab59071c9965f6b90146c40b. When there is a new ml5 release, the example sketches get wiped and new ones are generated. Perhaps it's best for me to create "copies" on the sketches in the `ima_ml` account so that the links don't go bad. Or I could just link to the ml5 website which, in theory, would have the web editor links updated. cc @joeyklee

**Comment by joeyklee** [comment]
@shiffman - I think if you link to them via the name, then the urls should resolve ok:

e.g.:

https://editor.p5js.org/ml5/sketches/UNET_webcam 

rather than the: https://editor.p5js.org/ml5/sketches/_Y9zm4MxkMs

**Comment by shiffman** [comment]
Oh right, yes, I forgot about this feature!!! 🤦‍♂️

**Comment by peilingjiang** [comment]
> 
> 
> Thank you! I believe I fixed this with [449526c](https://github.com/ml5js/Intro-ML-Arts-IMA/commit/449526ccc4ef4285ab59071c9965f6b90146c40b). When there is a new ml5 release, the example sketches get wiped and new ones are generated. Perhaps it's best for me to create "copies" on the sketches in the `ima_ml` account so that the links don't go bad. Or I could just link to the ml5 website which, in theory, would have the web editor links updated. cc @joeyklee

Oh there's actually another one in instructions section in Assignment. I changed them to name-based links with #70 .

**Comment by shiffman** [comment]
Thank you @peilingjiang!
